"""create pnr table

Revision ID: 15c58807cc7c
Revises: 9a2053912f77
Create Date: 2026-09-16 10:19:35.700816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c58807cc7c'
down_revision = '9a2053912f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PNR',
    sa.Column('PNR_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PNR_Code', sa.String(length=10), nullable=False),
    sa.Column('Booking_Office_Code', sa.String(length=10), nullable=False),
    sa.Column('POS_Travel_Agent_ID', sa.String(length=20), nullable=True),
    sa.Column('POS_City_Code', sa.String(length=3), nullable=True),
    sa.Column('POS_User_Type', sa.String(length=5), nullable=True),
    sa.Column('Creation_Date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('PNR_ID')
    )
    with op.batch_alter_table('PNR', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_PNR_PNR_Code'), ['PNR_Code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PNR', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_PNR_PNR_Code'))

    op.drop_table('PNR')
    # ### end Alembic commands ###
