"""create flight segment table

Revision ID: 15f98b9e9979
Revises: e23d735b9005
Create Date: 2026-09-18 12:01:33.748674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f98b9e9979'
down_revision = 'e23d735b9005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FLIGHT_SEGMENT',
    sa.Column('Segment_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PNR_ID', sa.Integer(), nullable=False),
    sa.Column('Flight_Number', sa.String(length=10), nullable=False),
    sa.Column('RBD_Class', sa.String(length=1), nullable=True),
    sa.Column('Flight_Date', sa.Date(), nullable=False),
    sa.Column('Boarding_Point', sa.String(length=3), nullable=False),
    sa.Column('Off_Point', sa.String(length=3), nullable=False),
    sa.Column('Action_Code', sa.String(length=2), nullable=True),
    sa.Column('Departure_Time', sa.Time(), nullable=True),
    sa.Column('Arrival_Time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['PNR_ID'], ['PNR.PNR_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Segment_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FLIGHT_SEGMENT')
    # ### end Alembic commands ###
