"""create agreement table

Revision ID: 6496900baaf3
Revises: 
Create Date: 2026-09-09 15:21:16.433852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6496900baaf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGREEMENT_TABLE',
    sa.Column('Agreement_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Partner_Code', sa.String(length=10), nullable=False),
    sa.Column('Response_Format_Option', sa.String(length=50), nullable=True),
    sa.Column('Allowed_Dates', sa.String(length=50), nullable=True),
    sa.Column('Allowed_Routes', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Agreement_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AGREEMENT_TABLE')
    # ### end Alembic commands ###
