"""add parser-sourced columns to flight_segment and passenger

Revision ID: 90d81272fb56
Revises: f2b1e1434851
Create Date: 2026-09-22 15:16:47.920259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d81272fb56'
down_revision = 'f2b1e1434851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FLIGHT_SEGMENT', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Airline_Code', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('Flight_Date_Raw', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('Number_In_Party', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Arrival_Day_Offset', sa.SmallInteger(), nullable=True))
        batch_op.alter_column('Flight_Date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('PASSENGER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Passenger_Type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('Email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Date_Of_Birth_Raw', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('Foid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PASSENGER', schema=None) as batch_op:
        batch_op.drop_column('Foid')
        batch_op.drop_column('Date_Of_Birth_Raw')
        batch_op.drop_column('Email')
        batch_op.drop_column('Passenger_Type')

    with op.batch_alter_table('FLIGHT_SEGMENT', schema=None) as batch_op:
        batch_op.alter_column('Flight_Date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('Arrival_Day_Offset')
        batch_op.drop_column('Number_In_Party')
        batch_op.drop_column('Flight_Date_Raw')
        batch_op.drop_column('Airline_Code')

    # ### end Alembic commands ###
