"""create inventory availability table

Revision ID: 9a2053912f77
Revises: b11292e05134
Create Date: 2026-09-15 13:49:59.606612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2053912f77'
down_revision = 'b11292e05134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVENTORY_AVAILABILITY',
    sa.Column('Inventory_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Flight_Number', sa.String(length=10), nullable=False),
    sa.Column('Flight_Date', sa.Date(), nullable=False),
    sa.Column('Boarding_Point', sa.String(length=3), nullable=False),
    sa.Column('Off_Point', sa.String(length=3), nullable=False),
    sa.Column('RBD_Class', sa.String(length=1), nullable=False),
    sa.Column('Segment_Status_Code', sa.String(length=5), nullable=True),
    sa.Column('Numeric_Availability', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Inventory_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVENTORY_AVAILABILITY')
    # ### end Alembic commands ###
