"""create osi table

Revision ID: 9edc3f64397c
Revises: 15f98b9e9979
Create Date: 2026-09-18 14:59:37.196074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edc3f64397c'
down_revision = '15f98b9e9979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OSI',
    sa.Column('OSI_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PNR_ID', sa.Integer(), nullable=False),
    sa.Column('Airline_Code', sa.String(length=3), nullable=False),
    sa.Column('Information_Text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['PNR_ID'], ['PNR.PNR_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OSI_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OSI')
    # ### end Alembic commands ###
