"""create message identifier table

Revision ID: b11292e05134
Revises: 6496900baaf3
Create Date: 2026-09-15 09:34:09.343561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11292e05134'
down_revision = '6496900baaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MESSAGE_IDENTIFIER',
    sa.Column('Msg_Identifier_Code', sa.String(length=3), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Msg_Identifier_Code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MESSAGE_IDENTIFIER')
    # ### end Alembic commands ###
