"""add passenger_id to osi table

Revision ID: bdfe79bdcd5b
Revises: 90d81272fb56
Create Date: 2026-09-22 16:39:21.811774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfe79bdcd5b'
down_revision = '90d81272fb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OSI', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Passenger_ID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'PASSENGER', ['Passenger_ID'], ['Passenger_ID'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OSI', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Passenger_ID')

    # ### end Alembic commands ###
