"""create passenger table

Revision ID: e23d735b9005
Revises: 15c58807cc7c
Create Date: 2026-09-18 10:33:50.063296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23d735b9005'
down_revision = '15c58807cc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PASSENGER',
    sa.Column('Passenger_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PNR_ID', sa.Integer(), nullable=False),
    sa.Column('Family_Name', sa.String(length=50), nullable=False),
    sa.Column('First_Name_Middle_Name', sa.String(length=100), nullable=True),
    sa.Column('Title', sa.String(length=10), nullable=True),
    sa.Column('Number_In_Party', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PNR_ID'], ['PNR.PNR_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Passenger_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PASSENGER')
    # ### end Alembic commands ###
