"""create ssr table

Revision ID: f2b1e1434851
Revises: 9edc3f64397c
Create Date: 2026-09-22 08:17:53.336620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b1e1434851'
down_revision = '9edc3f64397c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SSR',
    sa.Column('SSR_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PNR_ID', sa.Integer(), nullable=False),
    sa.Column('Passenger_ID', sa.Integer(), nullable=True),
    sa.Column('Segment_ID', sa.Integer(), nullable=True),
    sa.Column('SSR_Code', sa.String(length=4), nullable=False),
    sa.Column('Airline_Code', sa.String(length=3), nullable=True),
    sa.Column('Action_Code', sa.String(length=2), nullable=True),
    sa.Column('Free_Text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['PNR_ID'], ['PNR.PNR_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Passenger_ID'], ['PASSENGER.Passenger_ID'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['Segment_ID'], ['FLIGHT_SEGMENT.Segment_ID'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('SSR_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SSR')
    # ### end Alembic commands ###
